FROM php:8.2-apache

# 1. Copiar la carpeta 'config'
COPY ./config/ /var/www/html/config/

# 2. Copiar tu código principal al DocumentRoot
COPY ./frontend/ /var/www/html/

# Habilitar módulos necesarios
RUN docker-php-ext-install pdo pdo_mysql

# Asegurar permisos
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html